In [1]:
import numpy as np

# Copies or Views of objects


In [2]:
a = np.arange(10)

In [ ]:
print(a,b) 

In [3]:
# If we are assigning one array 'a' to another array 'b' then we are not copying it . But array 'b' is just another way to call
## array a => if we change any value in array 'a' then we automatically chanding values in array 'b' as well
b = a
a[1] = 15
print(a,b)

[ 0 15  2  3  4  5  6  7  8  9] [ 0 15  2  3  4  5  6  7  8  9]


In [4]:
# Below we can notice that both the variables have the same memory location
id(a) , id(b)

(2250682044112, 2250682044112)

* It seems like that by applying the assignment operator, the 2 variables have only have the distinct name but they have the same memory location. That is why change in one variable would also reflect in other variable. 
* Hence, by copying the two variables would have the distinct memory location

In [5]:
# Even when we slice an array, the object returned is a view of the original array
c = a[1:5]
print(c)

[15  2  3  4]


In [6]:
a[2] = 16
print(c)

[15 16  3  4]


In [7]:
# Hence if we want to generate a distinct array, then we will have to use the copy() function 
c = a.copy()
print(a,c)

[ 0 15 16  3  4  5  6  7  8  9] [ 0 15 16  3  4  5  6  7  8  9]


In [8]:
id(a) , id(c)

(2250682044112, 2250682114672)

In [9]:
a[0] = 14
print(a,c)
# Here we can notice that the change in 'a' is not reflecting in 'c'

[14 15 16  3  4  5  6  7  8  9] [ 0 15 16  3  4  5  6  7  8  9]


# Broadcasting
* The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.
* Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes

In [10]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [11]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

* We can think of the scalar b being stretched during the arithmetic operation into an array with the same shape as 'a'
* The stretching analogy is only conceptual. NumPy is smart enough to use the original scalar value without actually making copies so that broadcasting operations are as memory and computationally efficient as possible.
* code in the second example is more efficient than that in the first because broadcasting uses less memory during the multiplication