# Airthematic Operation

## Simple Operations

In [1]:
import numpy as np
from math import sin

In [2]:
# Addition: variable with a scaler
a = 2
print(a+2)

4


In [3]:
# Division - Simple numbers
8/5 #simple calculator

1.6

In [4]:
# Integer funtion
int(8/5)

1

* The int() function converts a number to its integer representation, discarding any decimal part. It does not round to the nearest integer. It simply truncates, meaning it cuts off everything after the decimal point.
* Therefore, int(1.5) results in 1, not 2.

In [6]:
# Created a one dimentional array
a = np.array([2])
b = np.array([10,20])
a , b

(array([2]), array([10, 20]))

In [7]:
# Division - Array / Array
a/b 

array([0.2, 0.1])

* Here we have divided an array with 1 element with an array with 2 elements. The resulting array have 2 elements. 

In [8]:
# Quotent & Remainder
print('Quotient: ', 8//5)
print('Remainder: ', 8%5)

Quotient:  1
Remainder:  3


In [9]:
# Power
5**2

25

In interactive mode and in Jupyter notebooks, the last printed expression is assigned to the variable _. This means that when you're using Python as a desk calculator, its somewhat easier to continue calculations. For example:

In [10]:
5 + _

30

In [11]:
# Assignment operator: we are assigning value to a variable 
x = 2

In [12]:
# Incremental operator
x += 2
x

4

* This operation adds 2 to the variable 'x'

In [14]:
# Decremental operator
y = 10 
y -= 5
y 

5

## One dimentional array 

**Arrays are mutable, we can change individual elements in them**

In [15]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [16]:
a[1] = 17 
a 

array([ 1, 17,  3,  4])

In [17]:
# Created one dimentional array of first n natural numbers including 0
# The upper limit value would not be the part of the array
a = np.arange(0,10)
b = np.arange(0,20,2) # To make sure that the gape between 2 subsequent numbers is 2
print('a: ', a)
print('b: ', b)

a:  [0 1 2 3 4 5 6 7 8 9]
b:  [ 0  2  4  6  8 10 12 14 16 18]


In [18]:
# Scaler addition to the array
a+4

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [19]:
# Scaler multiplication to the array
a*4

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [20]:
# Addition of 2 arrays
a+b

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

* This 'sin' is a numpy function, hence we are using 'np' in the start

In [21]:
# Used sin function from Numpy dictionary instead of using it from the Math liabrary
c = np.sin(b)
print(a*c)

[ 0.          0.90929743 -1.51360499 -0.83824649  3.95743299 -2.72010555
 -3.21943751  6.93425149 -2.30322653 -6.75888522]


## Multidimentional Array 

* **'arange'** function
* **'reshape'** function
* **'ones'** function

In [22]:
# One dimentional array
a = np.arange(0,10)
a.shape

(10,)

**Transforming one dimentional array into the multi dimentional array**

In [23]:
# Application of reshape function
# Transformed the one dimentional array into the two dimentional array
b = np.arange(0,10).reshape(2,5)
b.shape , b

((2, 5),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]))

In [24]:
# Here we have specified one column and the rows has to be accordingly 
# But one thing is for sure that it have converted the one dimentional array into the two dimentional array
a.reshape(-1,1) , a.reshape(-1,1).shape

(array([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]),
 (10, 1))

In [25]:
# Basically now it has 10 rows and 1 column 
a.reshape(10,1) , a.reshape(10,1).shape

(array([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]),
 (10, 1))

In [26]:
# Ones function
# Created one dimentional array of ones only 
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
# Ones function
# Created two dimentional array of ones only
c = np.ones((2,5))
c.shape , c

((2, 5),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [28]:
# Addition operator : 2 two dimentional arrays
A = np.arange(0,10).reshape(2,5)
B = np.ones((2,5))
A+ B

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [29]:
# Element wise multiplication operation of two 2-D arrays
# the resulting array will be the product of the corresponding elements from A & B
A = np.arange(0,10).reshape(2,5)
B = np.ones((2,5))
A , B , A*B

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]]))

**Dot Product**
* 1-D array: It would be a scaler value. Which would the sum product of the corresponding elements in the 2 arrays
* 2-D array: It would be the typical matrix multiplication which we have seen in Linear Algebra

In [30]:
# One dimentional arrays
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a.dot(b) , np.dot(a,b)

(70, 70)

In [31]:
# Two dimentional arrays
A = np.arange(1,5).reshape(2,2)
B = np.arange(5,9).reshape(2,2)
A, B , np.dot(A,B)

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[19, 22],
        [43, 50]]))

In [32]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Data Types in Python

* The integer numbers (e.g. 2, 4, 20) have type int
* fractional part (e.g. 5.0, 1.6) have type float

### Change datatype of a variable in a dataframe

In [33]:
import pandas as pd
import numpy as np

In [34]:
# Created a dataframe using an array
frame1 = pd.DataFrame(np.arange(16).reshape((4,4)), index = ['red', 'blue', 'yellow', 'white'] , columns = ['ball', 'pen', 'pencil', 'paper'])
frame1

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [35]:
frame1.dtypes

ball      int32
pen       int32
pencil    int32
paper     int32
dtype: object

In [36]:
# Here we have converted the datatype of variable "ball" from "integer" to "object"
frame1["ball"] = frame1["ball"].astype(object)

In [37]:
frame1.dtypes

ball      object
pen        int32
pencil     int32
paper      int32
dtype: object

**Another way to change the datatype**

In [ ]:
pd.to_numeric()

* It is a function provided by the pandas library in Python. Its main purpose is to convert a pandas object (like a Series or DataFrame column) to numeric values.

In [ ]:
pd.to_numeric(arg, errors='raise', downcast=None)

In [ ]:
df_norm["Price in lakhs"] = df_norm["Price in lakhs"].apply(lambda x : pd.to_numeric(x,errors = 'coerce'))

**arg** 
* This is the input data that you want to convert to numeric. It can be a pandas object like a Series or DataFrame column.
***
**errors** 
* This parameter specifies how to handle errors that may occur during the conversion. It can take three values:
* 'raise' (default) : Raises an error if any conversion error occurs.
* 'coerce' : Coerces errors to NaN (Not a Number). If a value can't be converted, it's set as NaN.
* 'ignore' : Ignores errors and returns the original data as is.
***
**Ques: "'ignore': Ignores errors and returns the original data as is." if it is not converted and assigned the original value doesn't that would make the variable non numeric?**
*  if there are non-numeric values in your data, the resulting Series will still contain those non-numeric values, making it a mix of numeric and non-numeric data

### Strings

**string.strip(char)**
* The strip() function in Python is a handy method for removing leading and trailing specified characters from a string
* string: Specified string from which we want to remove leading and training characters
* char: A string specifying a set of characters to remove from the beginning and end of the string. If omitted, it defaults to removing whitespace characters (spaces, tabs, newlines).
* strip() only removes characters from the beginning and end of the string, not from the middle.
* There are also lstrip() and rstrip() methods to strip characters only from the left or right sides of the string, respectively.

In [38]:
a = "    Gaurav    Manchanda"
a, type(a)

('    Gaurav    Manchanda', str)

In [39]:
a.strip()

'Gaurav    Manchanda'

In [40]:
b = "///Hello, World!///"

In [41]:
b.strip('/')

'Hello, World!'

In [44]:
b = a.strip()
b

'Gaurav    Manchanda'

In [45]:
c = "###Gaurav    Manchanda####"
c

'###Gaurav    Manchanda####'

In [47]:
# Here we have removed leading and trailing '#' characters
d = c.strip('#')
d

'Gaurav    Manchanda'

**Operations on Strings** 

In [48]:
z = 'Hello'
print(z)

Hello


In [49]:
j = "Hello"
print(j)

Hello


Strings can enclosed in single quotes ('...') or double quotes ("...") with the same result

In [50]:
# We can get the single quote in the string by using that with the back slash 
print('gaurav\'s')

gaurav's


In [51]:
print('gaurav\'saturday\'sunday')

gaurav'saturday'sunday


In [52]:
display('gaurav\'saturday\'sunday')

"gaurav'saturday'sunday"

In [53]:
display('gaurav\'s')

"gaurav's"

using \' helps us to use get commas in the texts

In [54]:
'"isn\'t," she said'

'"isn\'t," she said'

In [55]:
print('"isn\'t," she said')

"isn't," she said


In [56]:
print('"gaurav"')

"gaurav"


In [57]:
print("'gaurav'")

'gaurav'


Here we have seen that how to use the double quote within the single quote

**'\n' is used to divide the text in multiple lines**

In [58]:
x = 'first line\nsecond Line'
print(x)

first line
second Line


In [59]:
print('This is me\nI am 20 years old\nI am very hungry')

This is me
I am 20 years old
I am very hungry


In [60]:
print('c:\'some\name')

c:'some
ame


Here we want the output as : c:\some\name

In [62]:
print('c:\some\name')

c:\some
ame


Because in the second part we have \n, that is why it shifted the remaining part of the string in the next line. What we should do if we do not want to do that?

In [61]:
print(r'c:\some\name')

c:\some\name


**Hence 'r' in the front make sure that the text doesn't get split into the next line**

**Strings can be concatenated (glued together) with the + operator, and repeated with *:**

In [63]:
'un' *3

'ununun'

In [64]:
'Gau' + 'rav'

'Gaurav'

**Two or more string literals (that is, the values enclosed in quotes) placed next to each other are automatically concatenated:**

In [65]:
'Gau' 'rav' 'third'

'Gauravthird'

**Index of String** 
* Strings can be indexed (subscripted), with the first character having index 0

In [66]:
word = 'python'

In [67]:
word[0]

'p'

**Indices may also be negative numbers, which means to start counting from the end of the string.Negative indices start from -1:**

In [68]:
word[-1]

'n'

**Attempting to use an index that is too large results in an error. The same thing applied to 1-D arrays as well**

In [69]:
word[50]

IndexError: string index out of range

**Python strings are immutable (whereas arrays are mutable) which means they cannot be changed. Therefore, assigning a value to an indexed position in a string results in an error:**

In [72]:
word[2] = 'k'

TypeError: 'str' object does not support item assignment

**Slicing** 

* indicate a range in the format start:end, where the start position is included but the end position is excluded
* If you omit either position, the default start position is 0 and the default end is the length of the string:

In [73]:
word

'python'

In [74]:
word[1:3]

'yt'

In [75]:
word[:5]

'pytho'

In [76]:
word[1:]

'ython'

In [77]:
word[:3] + word[3:]

'python'

**However, when used in a range, an index that's too large defaults to the size of the string and does not give an error.**

In [78]:
word[2:100]

'thon'

**Note: words[200] would give an error but words[2:500] would not give any error** 

In [79]:
word[0:3] = 'ky'

TypeError: 'str' object does not support item assignment

**Check if a particulat pattern in a string**

In [80]:
a = 'saturday'

In [81]:
if 'sa' in a:
    print(a)
else:
    print("Not Available")

saturday


### Data Type : Boolian 
* True = 1 & False = 0

In [82]:
x = True
print(x)

True


In [83]:
True + True

2

In [84]:
y = (100 < 10)
print(y)

False


In [85]:
display(type(x) , type(y))

bool

bool

**In arithmetic expressions, True is converted to 1 and False is converted 0.**

In [86]:
display(True + True , True - True)

2

0

In [87]:
display(x + y , x*y)

1

0

# Increment and Decrement operator

* Here instead of creating a new array with the results, they will reassign the results in the same array
* We need these operations when we want to change the values in an array without generating the new one

In [88]:
a = np.arange(1,7)
a

array([1, 2, 3, 4, 5, 6])

In [89]:
# Increment operator
a += 1
a

array([2, 3, 4, 5, 6, 7])

In [91]:
# Decrement operator
a -= 1
a

array([ 3,  5,  7,  9, 11, 13])

In [90]:
# Multiplication operator
a *= 2
a

array([ 4,  6,  8, 10, 12, 14])

# Universal Function
* It works on an element by element basis in an array. 
* It acts individually on each single element of the input array to generate a corresponding result in a new output array. 
* Size of the output is same as the size of the input 

In [92]:
a = np.arange(1,9)
print(a , np.sqrt(a) , np.log(a) , np.sin(a))

[1 2 3 4 5 6 7 8] [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712] [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154] [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825]


# Aggregate Function 
* This performs an operation on a a set of values, an array for example, and produce a single result.

In [95]:
# Aggregate function available by default in python
a = np.arange(5,15)
print(a.sum() , a.min(), a.max(), a.mean() , a.std())

95 5 14 9.5 2.8722813232690143


In [96]:
# Numpy functions
np.sum(a) , np.min(a), np.max(a), np.mean(a), np.std(a)

95

In [ ]:
# These 3 are by default given by python and don't require to install any liabrray for them 
sum(a) , min(a) , max(a)

# Lists

* List can be written as a sequence of comma-separated values (items) between square brackets. Lists might contain items of different types, but usually the items all have the same type.
* Like strings (and all other built-in sequence types), lists can be indexed and sliced.
* Unlike strings, Lists are mutable
* It is a class and not the data type

In [101]:
weekdays= ['mon', 'tue','wed','thu','fri','sat']
weekdays

['mon', 'tue', 'wed', 'thu', 'fri', 'sat']

In [102]:
weekdays[0]

'mon'

In [103]:
weekdays[1:4]

['tue', 'wed', 'thu']

In [104]:
weekdays[0] = "Monday"

In [105]:
weekdays

['Monday', 'tue', 'wed', 'thu', 'fri', 'sat']

**Concatenation with the list**

In [106]:
weekdays + ['off', 'work']

['Monday', 'tue', 'wed', 'thu', 'fri', 'sat', 'off', 'work']

**Use the list's append( ) method to add new items to the end of the list:**

In [107]:
cubes = [1,8,27,65,125]

In [108]:
cubes.append(216)

In [109]:
cubes

[1, 8, 27, 65, 125, 216]

In [110]:
cubes[6] = []

IndexError: list assignment index out of range

* Using the 'append' method we can add only 1 additional item. 
* But if we want to add multiple items then instead we should use 'extend' method
* The extend() method can take an iterable object such as a list, tuple, or string, and add its elements to the end of the list.

In [111]:
cubes.extend([200,300,400])

In [112]:
cubes

[1, 8, 27, 65, 125, 216, 200, 300, 400]

In [113]:
# This way we have removed some specific elements from the list
cubes[6:7] = []

In [114]:
cubes

[1, 8, 27, 65, 125, 216, 300, 400]

* Hence to remove some items from the list we should use [:] method

In [115]:
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [116]:
letters[1:3] = ['B', 'C']
letters # Changed list items (2 old items replaced with 2 new items)

['a', 'B', 'C', 'd', 'e', 'f', 'g']

In [117]:
letters[2:5] = []

In [118]:
letters

['a', 'B', 'f', 'g']

In [119]:
letters[:] = []
letters  # Clear the entire list

[]

**Remove items from the list**

In [120]:
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [121]:
# This is another way to remove specific items from the list
letters.remove('c')

In [122]:
letters

['a', 'b', 'd', 'e', 'f', 'g']

# Class : Tuple 
* As we have seen that lists are mutables but tuple is a list which is immutable 
* Hence, string and tuple classes are immutable but array, sets & lists are mutable

In [123]:
y = 10,20
print(y, type(y))

(10, 20) <class 'tuple'>


Here we have seen that we can also create a tuple without using bracket as well

In [124]:
x[0] = 5  # Tuples are immutables

TypeError: 'bool' object does not support item assignment

In [125]:
# This is how we can assign values to varaibles using the list
z = [10, 20, 30]
a1 , a2 , a3 = z
display(a1,a2,a3)

10

20

30

In [126]:
# This is how we can assign values to varaibles using the tuple
k = (10, 20, 30)
a1 , a2 , a3 = k
display(a1,a2,a3)

10

20

30

In [127]:
a1 , q2 = k

ValueError: too many values to unpack (expected 2)

* We can assign variables to the list (or tuple), where the number of variables equals to the length of the list (or tuple)
* If we try to assign variables < length of the list (or tuple) , then we will get an error. But we can do so in a creative way (as mentioned below)

In [129]:
z = (10, 20, 30)*2
z

(10, 20, 30, 10, 20, 30)

In [130]:
a1 , a2 , a3 = z[0: 3]
display(a1,a2,a3)

10

20

30

In [131]:
a = [10,20,30]*3
b = (10,20,30)*2
display(a, b)

[10, 20, 30, 10, 20, 30, 10, 20, 30]

(10, 20, 30, 10, 20, 30)

* Here we have seen that unlike sets, the lists and tuple can have duplicate (repeated) values 

# Class : Sets

**Create a Set**

In [132]:
s1 = {'a' , 'b'}
display(s1 , type(s1))

{'a', 'b'}

set

In [134]:
s2 = {'b' , 'c'}
s2

{'b', 'c'}

### Various operations with sets**

In [135]:
s1 & s2 # Intersection

{'b'}

In [136]:
s1.intersection(s2) # Intersection

{'b'}

In [137]:
# This would give boolion output: True/False
s1.issubset(s2)

False

In [138]:
s3 = {'a', 'b', 'c', 'd'}

In [139]:
s1.issubset(s3)

True

In [140]:
s4 = {'a' , 'b' , 'c', 'd', 'a', 'b'}
print(s4) # Here we can see that although we tried to create set with duplicate items but that is not happening

{'b', 'd', 'c', 'a'}


In [141]:
# Difference of 2 sets
print(s1 -s2)

{'a'}


In [142]:
print ((s1 -s2) & s3)

{'a'}


In [143]:
s1.difference(s2).intersection(s3)

{'a'}

**Symmetric difference Operation '^'**
* The symmetric difference of two sets contains elements that are in either b or c, but not in both.
* It essentially combines elements that are unique to each set, excluding those that are shared.
* The ^ operator is exclusively for sets. Using it with other data types will result in an error.
* The symmetric difference operation is commutative, meaning b ^ c is equivalent to c ^ b

In [146]:
s1 , s2

({'a', 'b'}, {'b', 'c'})

In [147]:
s1^s2

{'a', 'c'}

**Convert a list into a set**

In [148]:
a = ['a' , 'b' , 'c' , 'd']

In [149]:
a , type(a)

(['a', 'b', 'c', 'd'], list)

In [150]:
b = set(a)

In [151]:
b , type(b)

({'a', 'b', 'c', 'd'}, set)

In [152]:
c = {'c' , 'd' , 'e', 'f'}

In [153]:
c , type(c)

({'c', 'd', 'e', 'f'}, set)

In [154]:
b^c

{'a', 'b', 'e', 'f'}

## Apply functions on lists 

In [155]:
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [156]:
len(letters)

7

In [157]:
letter1 = ['1','2','3','4','5']

In [158]:
for a in letter1:
    print(float(a))

1.0
2.0
3.0
4.0
5.0


In [160]:
sum(float(e) for e in letter1)

15.0

# numpy functions

### unique

In [161]:
import pandas as pd
import numpy as np

In [162]:
data_path = "C:\Personal\Carrier Path\Data_Scientist\Accumulated_content\Python\Practice_Data/"

In [163]:
data = pd.read_csv(data_path + "Churn_Modelling.csv")

In [164]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [165]:
y = data["Exited"].values
type(y)

numpy.ndarray

In [166]:
# We have applied the numpy formula on the array itself 
np.unique(y) # It provides unique values in the array 

array([0, 1], dtype=int64)

In [168]:
a = np.unique(y)
a

array([0, 1], dtype=int64)

In [169]:
# It provides both the unique values and their corresponding frequency 
# It provides 2 outputs 1) array of unique values 2) array of frequency
np.unique(y , return_counts = True) 

(array([0, 1], dtype=int64), array([7963, 2037], dtype=int64))

In [170]:
a, b = np.unique(y , return_counts = True) # As this code had 2 outputs, hence we have assigned them to 2 variables 

In [171]:
print(a)
print(b)

[0 1]
[7963 2037]


### Max

In [172]:
np.max(data["Age"].values)

92

# Data Type Conversion

### Various functions 

In [173]:
a = '2'
print(a, type(a))

2 <class 'str'>


In [174]:
b = float(a)
print(b, type(b))

2.0 <class 'float'>


# Assignment vs Equality operator

**Assignment operator "="**
* This operation is used for assignment, where we assign a value to a variable
***
**Equality operator"=="**
* used for equality comparison. It checks whether the values on both sides of the operator are equal