In [1]:
import numpy as np

# Conditional and Boolian Arrays
* Extracting elements from the array based on some conditions. 
* E.g. select all elements in the array which are less than 0.5
* Return would be a boolian array containing "True" values in the positions in which the values are less than 0.5
* Inserting the condition directly inside the square bracket , we extract all elements smaller than 0.5

In [2]:
A = np.random.random((4,4))

* In this code, the first 'random' refers to the 'random' module in the numpy library. And the second 'random' refers to the function which generates random floats from the uniform distribution between 0 & 1  
* The second bracket (4,4) is the tuple which satisfies that the resulting array should have 4 rows and 4 columns. 
* function np.random.random() creates an array of random numbers with the given shape, which is (4, 4) in this case.

In [3]:
A

array([[0.16674219, 0.60829062, 0.58035287, 0.09450288],
       [0.25822317, 0.67359557, 0.08811628, 0.80794704],
       [0.53561639, 0.74461319, 0.45724904, 0.55010711],
       [0.75061584, 0.56634556, 0.19172759, 0.75828133]])

In [4]:
A < 0.5

array([[ True, False, False,  True],
       [ True, False,  True, False],
       [False, False,  True, False],
       [False, False,  True, False]])

In [5]:
# This kind of filtering also works with the pandas dataframes as well
# In this way only those values are extracted from the array which have True value
A[A<0.5]

array([0.16674219, 0.09450288, 0.25822317, 0.08811628, 0.45724904,
       0.19172759])

# Shape Manipulation
* Here we can change the dimention of the array
* A function reshape() changes the dimention but that creates a new array and doesn't transform the existing array. 

In [6]:
# One dimentional array
a = np.random.random(12)
print(a , a.shape)

[0.07157909 0.32489626 0.63208047 0.27010388 0.60858077 0.2901543
 0.1765392  0.36758049 0.60375336 0.72679355 0.02813423 0.18199465] (12,)


**np.random.random(12) would create a one-dimentional array and the np.random.random((4,4)) would create 2-D array**

In [7]:
# Assign a tuple containing the dimenstion of new array.
a.shape = (3,4)
print(a , a.shape)

[[0.07157909 0.32489626 0.63208047 0.27010388]
 [0.60858077 0.2901543  0.1765392  0.36758049]
 [0.60375336 0.72679355 0.02813423 0.18199465]] (3, 4)


In [8]:
# This looks like a simple way to change the shape of an array
a.shape = (12)
print(a , a.shape)

[0.07157909 0.32489626 0.63208047 0.27010388 0.60858077 0.2901543
 0.1765392  0.36758049 0.60375336 0.72679355 0.02813423 0.18199465] (12,)


In [9]:
# alternate method to convert 1-D array into the 2-D array
b = np.arange(16).reshape(8,2)
print(b)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [10]:
b = b.ravel()
print(b , b.shape , len(b))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] (16,) 16


* The .ravel() function is used to flatten an array. It returns a 1-D array, which is a flattened version of the input array.\
* It's important to note that ravel has no effect on the original array and returns a new array with the same values but with one dimension less.

In [11]:
c = np.arange(12).reshape(3,4)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
c = c.reshape(1,12)
print(c , c.shape , len(c))

[[ 0  1  2  3  4  5  6  7  8  9 10 11]] (1, 12) 1


* Here we can notice that that the shape of an array (1,12) is different from (12,). In the array with shape (1,12) have lendth 1 but the array with shape (12,) have lendth 12
* Hence **ravel()** function is important

**Transposing a MATRIX**
* **c.transpose()** will not change the shape of a, but it is whole new object

In [14]:
c , c.shape

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]), (1, 12))

In [17]:
# Transposing a matrix
print(c , c.shape)
print(c.transpose() , c.transpose().shape)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]] (1, 12)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]] (12, 1)


**N-dimentional array -> 1 dimentional array : flatten the array**

In [18]:
c = np.arange(12).reshape(3,4)
c , c.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 (3, 4))

In [19]:
c.ravel() , c.ravel().shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

The Ravel() function is used to flatten the n-dimentional array. It means that it transforms the n-dimentional array into the 1-dimentional array.

**1-Dimentional Array -> N-Dimentional Array**

In [20]:
a = np.array([1,2,3,4,5,6])
a , a.shape

(array([1, 2, 3, 4, 5, 6]), (6,))

In [21]:
a.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [22]:
a.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6]])

* When using -1 in the reshape method of a NumPy array in Python, it's a way of telling NumPy to automatically calculate the size of that particular dimension.
* The value -1 is used as a placeholder to indicate that the size of that dimension should be inferred based on the size of the array and the sizes of the other dimensions.
* In your example, array.reshape(1, -1), you are reshaping the array into a 2D array with one row and an automatically calculated number of columns. The number of columns is inferred so that the total number of elements in the reshaped array remains the same as in the original array.

# Array Manipulation
* Create new arrays by joining or splitting arrays that are already defined

### Joining Arrays
* merge multiple arrays to form a new one that contains all of the arrays.
* Here we can apply **vertical staking** {it combines the second array as a new rows of the first array} and **horizontal staking** {it combines the second array as new columns of the first array}

### Vertical Staking 

In [23]:
A = np.ones(9).reshape(3,3)
B = np.zeros(9).reshape(3,3)
A, B

(array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]))

In [24]:
np.vstack((A,B))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
# Vertical staking is similar to the concatenation with respect to the axis = 0 which is rows 
np.concatenate([A,B], axis =0)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Horizontal Stacking 

In [26]:
np.hstack((A,B))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [27]:
np.concatenate([A,B] , axis =1)

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

### **Column_stack() and row_stack()**
* These functions are used with 1 dimentional arrays to form a new 2 dimentional array

In [28]:
# 3 one dimentional arrays
a = np.array([0,1,3])
b = np.array([3,4,5])
c = np.array([6,7,8])
a , b , c

(array([0, 1, 3]), array([3, 4, 5]), array([6, 7, 8]))

In [31]:
np.hstack((a,b,c)) , np.hstack((a,b,c)).shape

(array([0, 1, 3, 3, 4, 5, 6, 7, 8]), (9,))

In [32]:
# Here we can see that through the verticle staking we have build 2-D array using 3 1-D arrays
np.vstack((a,b,c)) , np.vstack((a,b,c)).shape

(array([[0, 1, 3],
        [3, 4, 5],
        [6, 7, 8]]),
 (3, 3))

In [33]:
# 'a' is the first column, 'b' is the second column, 'c' is the third column
# Here 3 one dimential arrays with size 3 are making a 2 dimentional array with size 3*3
np.column_stack((a,b,c)) 

array([[0, 3, 6],
       [1, 4, 7],
       [3, 5, 8]])

In [34]:
# 'a' is the first row, 'b' is the second row, 'c' is the third row
np.row_stack((a,b,c)) 

array([[0, 1, 3],
       [3, 4, 5],
       [6, 7, 8]])

### Concatenating 2 arrays

In [35]:
# Here we have manually created a 2 dimentional arrays
array_1 = np.array([[1,2],[3,4],[5,6]])
array_2 = np.array([[7,8],[9,10],[11,12]])
array_1 , array_2

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]]))

In [36]:
# We can also pass a tuple of arrays instead of the list of arrays => both does the same thing 
X = np.concatenate((array_1 , array_2) , axis = 1)
X

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

In [37]:
X = np.concatenate([array_1 , array_2] , axis = 1)
X

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

In [38]:
Y = np.concatenate((array_1 , array_2) , axis = 0 )
Y

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

### Splitting Arrays
* Divide an array into several parts
* Split the array horizontally means the width of the array is divided into 2 parts : 4x4 matrix to 4x2 matrices
* Split the array vertically means the height of the array is divided into 2 parts : 4x4 matrix to 2x4 matrices


In [39]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
[b,c] = np.hsplit(A,2)
A , b , c

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))

In [41]:
[d,e] = np.vsplit(A,2)
A , d, e

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

* **split() function** allows us to split the array into non symmetrical parts 
* **np.split(A , [1,3] , axis = 1)** : Here A : array to be split, axis =1 / 0 (column / rows), Here the index in the middle defines that which columns to include in the second matrix. Where [1,3] means to include the 1st and the 2nd column 
   

In [42]:
# Column wise split
[A1, A2, A3] = np.split(A,[1,3], axis =1)
A , A1,A2,A3

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]))

In [43]:
# Row wise split
[A1,A2,A3] = np.split(A , [1,2] , axis = 0)
A , A1,A2,A3

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [44]:
# Split with 1-D array
a = np.arange(10)
[b,c,d] = np.split(a, [3,6])
a, b,c,d

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2]),
 array([3, 4, 5]),
 array([6, 7, 8, 9]))