In [1]:
import numpy as np
import pandas as pd

## Create an Array 

### One Dimentional Array 

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

*  Used the array() function to define new ndarray
*  Under the array we pass a list or a tuple (but not the set): list is written in square bracket

In [3]:
b = np.array((1,2,3))
b

array([1, 2, 3])

In [7]:
b.shape

(3,)

In [5]:
c = np.array({1,2,3})
c

array({1, 2, 3}, dtype=object)

In [6]:
c.shape, type(c)

((), numpy.ndarray)

### Two Dimentional Array 

In [8]:
a.dtype

dtype('int32')

* dtype is an 'attribute' not a function
* type() : it tells the type of the object, whether that is array, list or dataframe. 
* dtypes : it tells about the datatype of elements in the array. 

In [9]:
print(a.shape , a.size , a.ndim) 

(3,) 3 1


* 3 other attributes (its size, shape and its rank) must to know about the ndarray

In [10]:
b = np.array([[1.3, 2.4], [0.3, 4.1]])
print(b, b.shape, b.ndim , b.size)

[[1.3 2.4]
 [0.3 4.1]] (2, 2) 2 4


* Creating 2 dimentional array
* Here there is one list which has 2 elements and both are lists. The first list becomes the first row and the second list becomes the second row
* Here the array has 4 elements and not 2 (consider this in terms of matrix)

In [ ]:
# Array function not only accepts lists but tuple as well
a = np.array((1,2,3))
c = np.array(((1,2,3), (4,5,6)))
print(a.size, a.ndim, a.shape)
print(c.size, c.ndim, c.shape)

In [11]:
# By defining the datatype in the array we can define that what kind of data is there in the array.
g = np.array([[1,2,3], [4,5,6]] , dtype = complex)    
print(g)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


### Numbers generator 

**Non random numbers generators** 

In [12]:
# the zero() function creates an array of zeros and its dimention defined by the shape argument
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# to generate an array of sequence of numbers 
# The array doesn't include the value equals to the upper limit of the range passed in this function
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [27]:
# Make sure that difference between subsequent numbers would be 2
# Here we didn't defined the length of the array it would be dependent on various parameters we choose
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

**Random numbers generators**

In [16]:
# This is used to generate random numbers from the uniform distribution with range 0 to 1 
# But everytime we run this code we get different set of numbers 
np.random.random(4)

array([0.06622161, 0.97431486, 0.43489051, 0.23692959])

In [ ]:
# What if we want to get the same set of random numbers everytime
rng = np.random.RandomState(20) # First we created an instance by defining the random state
numbers = rng.random(3) # Used the instance to create the random numbers
numbers

* t0: Run the code 'rng = np.random.RandomState(20)'
* t1: Run the code 'rng.random(3)', 3 times (or as many times you want)
* t3: Run the code 'rng = np.random.RandomState(20)'
* t4: Run the code 'rng.random(3)', 3 times (or as many times you want) => Here we will get the same sequence of arrays as we get in t1

In [25]:
np.random.RandomState(11).random(3)

array([0.18026969, 0.01947524, 0.46321853])

In [28]:
np.arange(2,10,0.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ,
       8.5, 9. , 9.5])

In [29]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

* Here first 2 arguments are the range and the last argument tells that in how many pieces we need to split this range.
* Here the upper limit can be the value in the array.
* This will provide evenly spaced numbers. 

In [ ]:
# There is a module name "numpy.random module". And there is a function called random() in this module 
np.random.random(10)

* Here 'numpy' is liabrary
* 'random' is a module in the liabrary
* Within the module 'random' we have a function called 'random()'
* This function creates 10 random numbers between 0 and 1 

In [30]:
# There are 2 ways to create a multidimentional array.
## Define the shape within the function
np.random.random((3,3))
## Definie the shape at the end of the function using reshape() function
a = np.random.random(8).reshape(4,2)
print(a)

[[0.4760966  0.88811531]
 [0.69145872 0.50586519]
 [0.94715515 0.90743992]
 [0.60092089 0.69138807]]


In [35]:
# Extracted first row
a[0] , a[-4]

(array([0.4760966 , 0.88811531]), array([0.4760966 , 0.88811531]))

In [34]:
a[[1,2,3]]

array([[0.69145872, 0.50586519],
       [0.94715515, 0.90743992],
       [0.60092089, 0.69138807]])

In [36]:
a = np.arange(10,16)
a

array([10, 11, 12, 13, 14, 15])

In [37]:
# Filtering from array based on a sequence
# 0:15 picks 5 numbers with index 0, 1, 2 ,3 & 4 which are 10,11,12,13,14. Then it picks the first number, skips the second and then picks the 3rd number
a[0:5:2]

array([10, 12, 14])

In [38]:
a[0:5]

array([10, 11, 12, 13, 14])

In [39]:
# Created function and later we will pass objects for which scaler division is allowed
def foo(x):
    return x/2

In [41]:
t = (1,2,3)
print(type(t) , t/2)
# For tuple the scaler multiplication or the scaler division are not allowed. Hence, the above formula would not apply here

TypeError: unsupported operand type(s) for /: 'tuple' and 'int'

In [40]:
s = {1,2,3,4}
print(type(s) , s/2)

TypeError: unsupported operand type(s) for /: 'set' and 'int'

In [42]:
a = np.arange(10)
print(type(a) , a/2)

<class 'numpy.ndarray'> [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


**Note: Hence, we have seen that scaler muliplication doesn't applies to sets and tuples but to the arrays**

In [43]:
A = np.random.random((4,4))
A

array([[0.96236266, 0.15857018, 0.31074468, 0.11091162],
       [0.6248295 , 0.84473509, 0.91059457, 0.5209061 ],
       [0.88249603, 0.2866121 , 0.65960194, 0.18323711],
       [0.38956789, 0.5913872 , 0.40908893, 0.6916598 ]])

In [44]:
# The custom formula applied to the array
foo(A)

array([[0.48118133, 0.07928509, 0.15537234, 0.05545581],
       [0.31241475, 0.42236754, 0.45529728, 0.26045305],
       [0.44124801, 0.14330605, 0.32980097, 0.09161856],
       [0.19478394, 0.2956936 , 0.20454446, 0.3458299 ]])

In [45]:
foo(a)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [47]:
# Here as i used the single bracket, hence it is a 1-D array
a = np.random.random(12)
a , a.shape

(array([0.71841755, 0.88165728, 0.93669599, 0.58346447, 0.16838866,
        0.55885193, 0.00230508, 0.58545014, 0.92685402, 0.69196803,
        0.35960892, 0.08702539]),
 (12,))

In [48]:
# Here we have passed a tuple, hence it is a matrix
np.random.random((4, 3)) , np.random.random((4, 3)).shape

(array([[0.76952818, 0.41261286, 0.2865208 ],
        [0.48407617, 0.93153722, 0.9109652 ],
        [0.75973709, 0.29997259, 0.07878365],
        [0.26344853, 0.21331753, 0.88188419]]),
 (4, 3))

In [49]:
# Resulting 2-D array would have 4 rows
data = np.array([[0.8 , 0.76 , 0.22],[0.12 , 0.54, 0.06],[0.06, 0.85, 0.92],[0.58, 0.23, 0.45]])
data

array([[0.8 , 0.76, 0.22],
       [0.12, 0.54, 0.06],
       [0.06, 0.85, 0.92],
       [0.58, 0.23, 0.45]])

**Note: We can also save the numpy data as 'npy' file and load that as well** 

In [ ]:
# Saved the data 
# Here we have 2 arguments: first (name of the array) & second (the array which we want to save)
np.save('data_1' , data)

In [ ]:
# Load the data
# It have just one argument which is the name of the saved array
data_2 = np.load('data_1.npy')

**np.save & np.load**

In [ ]:
data_2

**Create an array which is a copy of another object (in terms of rows, columns & datatype)** 

In [50]:
# Data imported
file_path = "C:\Personal\Carrier Path\Data_Scientist\Accumulated_content\Python\Practice_Data/"
data = pd.read_csv(file_path + 'project_1.1.csv')
data.drop(columns = ['Unnamed: 0'] , inplace = True)
data.head()

n_bhk  surface  price  club_house  school  hospital  mall  park  pool  gym  \
0    1.0    492.0    3.9           1       1         1     1     1     1    1   
1    2.0    774.0    6.5           1       1         1     1     1     1    1   
2    3.0    889.0    7.4           1       1         1     1     1     1    1   
3    3.0   1018.0    8.9           1       1         1     1     1     1    1   
4    2.0    743.0    7.4           1       1         1     1     1     1    1   

   ...  sa3  sa4  sa5  sa6  sa7  sa8  sa9  sa10  sa11  sa12  
0  ...    0    0    0    0    0    0    0     0     0     0  
1  ...    0    0    0    0    0    0    0     0     0     0  
2  ...    0    0    0    0    0    0    0     0     0     0  
3  ...    0    0    0    0    0    0    0     0     0     0  
4  ...    0    0    0    0    0    1    0     0     0     0  

[5 rows x 22 columns]

In [51]:
# Correlation matrix
correl = data[['n_bhk','surface','price','club_house','school','hospital','mall','park','pool','gym']].corr()
correl

n_bhk   surface     price  club_house    school  hospital  \
n_bhk       1.000000  0.875115  0.695072    0.041387 -0.009743 -0.009743   
surface     0.875115  1.000000  0.882181    0.081925 -0.039362 -0.039362   
price       0.695072  0.882181  1.000000    0.020031 -0.043156 -0.043156   
club_house  0.041387  0.081925  0.020031    1.000000  0.104627  0.104627   
school     -0.009743 -0.039362 -0.043156    0.104627  1.000000  1.000000   
hospital   -0.009743 -0.039362 -0.043156    0.104627  1.000000  1.000000   
mall       -0.009743 -0.039362 -0.043156    0.104627  1.000000  1.000000   
park        0.022201  0.052562  0.078556    0.246441  0.025784  0.025784   
pool        0.224389  0.266961  0.292248    0.378142  0.136320  0.136320   
gym         0.006450  0.064589  0.056582    0.363402  0.087657  0.087657   

                mall      park      pool       gym  
n_bhk      -0.009743  0.022201  0.224389  0.006450  
surface    -0.039362  0.052562  0.266961  0.064589  
price      -0.043156  0.078556  0.292248  0.056582  
club_house  0.104627  0.246441  0.378142  0.363402  
school      1.000000  0.025784  0.136320  0.087657  
hospital    1.000000  0.025784  0.136320  0.087657  
mall        1.000000  0.025784  0.136320  0.087657  
park        0.025784  1.000000  0.189147 -0.071196  
pool        0.136320  0.189147  1.000000  0.347927  
gym         0.087657 -0.071196  0.347927  1.000000

In [52]:
# We have build an infrastructure (in terms of an array) coping the object 'correl'. We also specified the datatype as well
# Every element is False because because value is 0 
mask = np.zeros_like(correl , dtype = np.bool_)
mask

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [53]:
np.zeros_like(correl )

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

**np.zeros_like(data , dtype)**
* This function creates an array of zeros with the same shape and data type as the input array.
* **data** : This is an object. The new array will have the same shape and data type as this object.
* **dtype=np.bool_** : This specifies the data type of the new array. In this case, it's set to boolean (bool_).
***
**Ques: Why initially all the entries in the matrix 'mask' have 'False' label?**
* When creating a boolean array using np.zeros_like with the dtype=np.bool_ parameter, the default fill value is False

# Change values in an array

In [54]:
a = np.array([[1,2,3] , [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.triu_indices_from(a)

**triu_indices_from()**
* This function, triu_indices_from, returns the indices for the upper triangular part of a 2-D array. 

In [ ]:
# It assigns the value to those indices which were identified by 'np.triu_indices_from(a)'
a[np.triu_indices_from(a)] = 10

In [ ]:
a

# Create dictionary using the Zip function 

In [55]:
# List 
name = ['A', 'B', 'C', 'D']
Number = [12, 13, 14, 15]

In [56]:
# Here 'name' is the key and 'Number' is the values
pair = zip(name, Number)
pair

In [57]:
# Created a set of the zip elements
set(pair)

{('A', 12), ('B', 13), ('C', 14), ('D', 15)}

In [58]:
type(set(pair))

set

In [59]:
# Created a dictionary using the zip 
dict(pair)

{}

In [60]:
dict(zip(name, Number))

{'A': 12, 'B': 13, 'C': 14, 'D': 15}

* Here we can see the difference between a set and the dictionary
* A dictionary have a key and a value

**Example:1 Creating Dictionary using for loop**

In [61]:
# we initialised the dictionary object
dictionary = dict()
dictionary

{}

In [62]:
# This is also the way we can create a dictionary quite easily. And it also open up it to use the for loop 
dictionary[2] = "Gaurav"
dictionary

{2: 'Gaurav'}

In [63]:
name = ['A', 'B', 'C', 'D']
Number = [12, 13, 14, 15]

In [64]:
num_dict = dict()

In [65]:
for a,b in zip(name , Number):
    num_dict[a] = b 

In [66]:
num_dict

{'A': 12, 'B': 13, 'C': 14, 'D': 15}

# Map() function

# Meshgrid

* Meshgrid turns one-dimensional NumPy arrays into grids called matrices. 
* If we pass two NumPy arrays into meshgrid, we get two matrices back. Below we use meshgrid to create two grids from two array.
* The grids, or matrices, that meshgrid generates are suitable for matrix math and plotting, among other things.

In [67]:
array_a = [1,2,3,4,5]
array_b = [10, 20, 30 , 40]

In [68]:
XX , YY = np.meshgrid(array_a , array_b)

In [69]:
XX , YY

(array([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]),
 array([[10, 10, 10, 10, 10],
        [20, 20, 20, 20, 20],
        [30, 30, 30, 30, 30],
        [40, 40, 40, 40, 40]]))

* In the first matrix, every column has a different number. In the second matrix, every row has a different number. Placing these two matrices on top of one another gives us every possible combination between the values of array_a and the values of array_b. 