In [1]:
import numpy as np

### How to manipulate a Numpy Array
* Select elements from the array
* change its value 

# INDEXING 
* Use square brackets ([]) to index the elements of the array
* When we create a new array, an appropriate scale index is also automatically created e.g. if an array have 5 elements then from left to right the indexes would be {0,1,2,3,4} and from right to left it would be {-6, -5, -4, -3, -2, -1} 

In [ ]:
a = np.arange(0,16,2)
print(a, '4th element is = ',a[3] , a[-1] , a[-8])

In [ ]:
# To select multiple items at once, we can pass array of indexes in square bracket
print(a[[0,2,4]])

* A matrix is defined by 2 axes where axis = 0 represents the rows & axis = 1 represents the columns.
* Indexing in case of Matrix is represented by a pair of values. Where the first value is the index of the row and the second value is the index of the column.  
* To access value from the Matrix, still use the square bracket [row index, column index]

In [ ]:
A = np.arange(0,10).reshape(5,2)
print(A , A[2,1])

# Slicing
* It allows us to extract portions of an array to generate new array
* For extraction we will use a sequence of numbers separated by colons(:) within square bracket [ : ]
* Here alos within the square bracket, the lower limit is included and the external limit is excluded

In [ ]:
a = np.arange(0,15)
print("These are 2nd, 3rd, 4th & 5th element : ",a[1:5])

In [ ]:
# extract alternative numbers
a[1:5:2]

* [lowest index value , highest index value , increment rate]
* By default lowest index value = 0
* By default highest index value = size of the array
* By default the incremental rate = 1 
* In case of Matrix (2 dimentional array). We will specify the index syntax for columns and rows separately

In [ ]:
a[::2]

In [ ]:
a[:5:2]

In [ ]:
a[:5:]

In [ ]:
A = np.arange(0,20).reshape(4,5)
A[1:4 , 2:5]

# Iterating an Array
* Use the 'for' construct

In [ ]:
a = np.arange(0,10)

In [ ]:
for i in a:
    print(i)

In [5]:
A = np.arange(0,20).reshape(4,5)
A , A.shape

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 (4, 5))

In [7]:
A.flat

In [3]:
# Loop with respect to rows in a 2-d array
for row in A : 
    print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [4]:
# Loop with respect to elements elements in a 2-d array
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


* Apply in iteration to apply a function on the rows or on the columns . 
* Launch  an aggregate function that returns a value for every single row or every single column. 
* For this we use :*apply_along_axis()*   --  It is a function
* axis = 0 => iteration evaluates the elements across rows
* axis = 1 => iteration evaluates the elements across columns
* np.mean , np.max etc. are the functions defined in the numpy liabrary

In [9]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [8]:
np.apply_along_axis(np.mean , axis = 0 , arr = A)

array([ 7.5,  8.5,  9.5, 10.5, 11.5])

In [10]:
np.apply_along_axis(np.mean , axis = 1 , arr = A)

array([ 2.,  7., 12., 17.])

In [12]:
# Defining own functions
def foo(x):
    return x/2

In [13]:
# Here doesn't matter whether i iterate column wise or rows wise. It applies the function to all the elements in the matrix and 
## gives the resulting maipulated matrix.
np.apply_along_axis(foo , axis =1 ,arr = A)

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. , 9.5]])

In [14]:
np.apply_along_axis(foo , axis =0 ,arr = A)

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. , 9.5]])